### PR TITLE
added files property in package.json

### PR DESCRIPTION
**Pull request by ASaiAnudeep**
- makes the npm package lighter
- removes `test.js` from the published package

### CODE REVIEW

**Comment by ASaiAnudeep** [comment]
@ethanent could you please review this PR when you get a chance.

**Comment by ASaiAnudeep** [comment]
@ethanent could you please review this PR when you get a chance.

**Comment by ASaiAnudeep** [comment]
@ethanent could you please review this PR when you get a chance.

**Comment by ethanent** [comment]
Thank you :)

**Pull request merged**
